from .core import CoreRoutesMixin
from .admin import AdminRoutesMixin
from .gauntlet import GauntletRoutesMixin
from .tournament import TournamentRoutesMixin
from .clubs import ClubsRoutesMixin
from .calendar import CalendarRoutesMixin
from .trust import TrustRoutesMixin
from .auth import AuthRoutesMixin
from .player import PlayerRoutesMixin
from .public import PublicRoutesMixin
