name: Expression Diagnostic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Condition
        if: (true || false) && true
        run: echo ok
